/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2019 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_CMPERR_H
# define HEADER_CMPERR_H

# ifndef HEADER_SYMHACKS_H
#  include <openssl/symhacks.h>
# endif

# include <openssl/opensslconf.h>

# ifndef OPENSSL_NO_CMP

#  ifdef  __cplusplus
extern "C"
#  endif
int ERR_load_CMP_strings(void);

/*
 * CMP function codes.
 */
#  define CMP_F_CMP_CTX_SET1_CAPUBS                        100
#  define CMP_F_CMP_CTX_SET1_EXTRACERTSIN                  101
#  define CMP_F_CMP_CTX_SET1_NEWCLCERT                     102
#  define CMP_F_CMP_CTX_SET1_RECIPNONCE                    103
#  define CMP_F_OSSL_CMP_ASN1_OCTET_STRING_SET1            104
#  define CMP_F_OSSL_CMP_ASN1_OCTET_STRING_SET1_BYTES      105
#  define CMP_F_OSSL_CMP_CTX_GET1_CAPUBS                   106
#  define CMP_F_OSSL_CMP_CTX_GET1_EXTRACERTSIN             107
#  define CMP_F_OSSL_CMP_CTX_PUSH1_EXTRACERTSOUT           108
#  define CMP_F_OSSL_CMP_CTX_PUSH_FREETEXT                 109
#  define CMP_F_OSSL_CMP_CTX_SET0_NEWPKEY                  110
#  define CMP_F_OSSL_CMP_CTX_SET0_PKEY                     111
#  define CMP_F_OSSL_CMP_CTX_SET0_REQEXTENSIONS            112
#  define CMP_F_OSSL_CMP_CTX_SET1_CLCERT                   113
#  define CMP_F_OSSL_CMP_CTX_SET1_EXPECTED_SENDER          114
#  define CMP_F_OSSL_CMP_CTX_SET1_EXTRACERTSOUT            115
#  define CMP_F_OSSL_CMP_CTX_SET1_ISSUER                   116
#  define CMP_F_OSSL_CMP_CTX_SET1_LAST_SENDERNONCE         117
#  define CMP_F_OSSL_CMP_CTX_SET1_NEWPKEY                  118
#  define CMP_F_OSSL_CMP_CTX_SET1_OLDCLCERT                119
#  define CMP_F_OSSL_CMP_CTX_SET1_P10CSR                   120
#  define CMP_F_OSSL_CMP_CTX_SET1_PKEY                     121
#  define CMP_F_OSSL_CMP_CTX_SET1_PROXYNAME                122
#  define CMP_F_OSSL_CMP_CTX_SET1_RECIPIENT                123
#  define CMP_F_OSSL_CMP_CTX_SET1_REFERENCEVALUE           124
#  define CMP_F_OSSL_CMP_CTX_SET1_SECRETVALUE              125
#  define CMP_F_OSSL_CMP_CTX_SET1_SERVERNAME               126
#  define CMP_F_OSSL_CMP_CTX_SET1_SERVERPATH               127
#  define CMP_F_OSSL_CMP_CTX_SET1_SRVCERT                  128
#  define CMP_F_OSSL_CMP_CTX_SET1_SUBJECTNAME              129
#  define CMP_F_OSSL_CMP_CTX_SET1_TRANSACTIONID            130
#  define CMP_F_OSSL_CMP_CTX_SET_PROXYPORT                 131
#  define CMP_F_OSSL_CMP_CTX_SET_SERVERPORT                132
#  define CMP_F_OSSL_CMP_CTX_PUSH1_SUBJECTALTNAME          133

/*
 * CMP reason codes.
 */
#  define CMP_R_INVALID_ARGS                               100
#  define CMP_R_INVALID_CONTEXT                            101
#  define CMP_R_MULTIPLE_SAN_SOURCES                       102
#  define CMP_R_NULL_ARGUMENT                              103

# endif
#endif
